[package]
name = "rust_introduction"
version = "0.1.0"
authors = ["Kalin Dimitrov <kalinsky.vf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
